modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="mud_backport"
version="1.1.5"
displayName="Mud Backport"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Snubig1"
description='''
A not so quick backport of mud and its distant relatives to 1.18.2
'''

[[dependencies.mud_backport]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




